{
  "sksl": {
    "entrypoint": "srcBlendModeGreater0_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uResolution;\nuniform shader uTexture1;\nuniform half2 uTexture1_size;\nuniform shader uTexture2;\nuniform half2 uTexture2_size;\n\nvec4 fragColor;\n\nvoid FLT_main()\n{\n    vec2 uv = flutter_FragCoord.xy / uResolution;\n    vec4 colorA = uTexture1.eval(uTexture1_size * ( uv));\n    vec4 colorB = uTexture2.eval(uTexture2_size * ( uv));\n    vec4 result = vec4((colorA.x * (1.0 - colorB.x)) + colorB.x, (colorA.y * (1.0 - colorB.y)) + colorB.y, (colorA.z * (1.0 - colorB.z)) + colorB.z, 1.0);\n    fragColor = result;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 0,
        "name": "uTexture1",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 1,
        "name": "uTexture2",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uResolution",
        "rows": 2,
        "type": 10
      }
    ]
  }
}